---
name: Docker Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.deepsource.toml'
      - 'setup_ros_env.sh'
  pull_request:
    paths:
      - 'README.md'
      - '.deepsource.toml'
      - 'setup_ros_env.sh'

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-docker-build:

    name: Call Docker Build

    uses: faizansana/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main

    permissions:
      contents: read
      packages: write # needed to push docker image to ghcr.io
      pull-requests: write # needed to create and update comments in PRs
    
    secrets:

      # Only needed if with:dockerhub-enable is true below
      # https://hub.docker.com/settings/security
      dockerhub-username: ${{ secrets.DOCKER_HUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    with:
      
      dockerhub-enable: true
      ghcr-enable: true

      image-names: |
        ghcr.io/${{ github.repository }}
        docker.io/${{ github.repository }}
